version: '3.1'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_bkup:/backup

  backend:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    restart: always
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - NODE_ENV=development
      - MAILGUN_KEY=
    
volumes:
  postgres_data:
