version: '3.1'

services:
  postgres:
    image: postgres
    ports:
    - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  membership:
    build: .
    image: nkansal/membership
    ports:
      - "8080:8080"
    links:
      - postgres
      - redis
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
      - HOST=localhost