version: '3.1'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    image: nkansal/backend
    ports:
      - "8080:8080"
    links:
      - postgres
    restart: always
    env_file:
      - node.env

  nginx:
    build: ./static
    image: nkansal/static
    links:
      - backend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/etc/nginx/certs:ro"
      - "./certs-data:/data/letsencrypt"

volumes:
  postgres_data:
